language: node_js
branches:
  only:
  - gh-pages
env:
  global:
    - URL="https://w3c.github.io/webpayments-methods-card/echidna-manifest.txt"
    - DECISION="https://www.w3.org/2016/04/14-wpwg-minutes#item02"
    - secure: JVXBKlt3vDjGukkZwlYS8R8xwdV6QqVvshVjvTG/CfOeBhw5m6ZTMycXM2a/iR49OfomZRsfbV/JDxM3i4/fjGo4+FrtV6ei8SQfzymTBnYuxAO2v3aeN04daHhE9or0zXP75MFvpqpT7qSoAEMKC+Xpluybs7AZdG6L//10cbhqPrGUxrNaKGz/GChJrXLhGb8Np2upNWWwYAk/Lo8dKLrTUAT8Xr/1jMJ0j4yFh6u/OyZ/plb9pGjpWgyC02zKfHmkz7XpIrnXHPXUy7uKcTlD/wgAkw1801VmC6CHvawBtkwBny91EFHKObImw1tYTlj0aUn7zb3mZ9R6b5H1e1PPjWaqtl50SG02FQjt0PD7sVJsLzzjBYXupYA76MCYQkq24l36Xgr2+3Xb2xX+U/OIfeZaOADrGpyGwwgnf2XbJWp/uMBtMjIUJNxeH04a/GeE1ZOrDkMSir0NLr50WuK0tkbxj3EfdlvJoZc7YkzXzv7ygZ+Vc/o3V6GrCHmmGkLVS6C+mgUXbxybTlL5/FkLNN3JAQFWQmophoAH9QipY50rJP609DlDDqpBlmFlA4eNo9+bBUGNl+hW2oEHg4puQz8Dz9WehhlNg77nimn3ZQFX+I4itZUedzw3JOSWKChG6GUIMQpVu/x3j4PxKUP4ToBtjRbXPh/FciC+Yag=
script:
  - echo "ok"
after_success:
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
